# Generated by Django 5.2.8 on 2025-11-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='logo',
        ),
    ]
