# Generated by Django 5.2.8 on 2026-08-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_vendor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vendor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='require_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_logos/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
