# Generated by Django 5.2.8 on 2026-08-21 10:01

from django.conf import settings
from django.db import migrations, models


def repair_missing_support_tables(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        tables = set(schema_editor.connection.introspection.table_names(cursor))
    for model_name in ("Ticket", "TicketMessage"):
        model = apps.get_model("support", model_name)
        if model._meta.db_table not in tables:
            schema_editor.create_model(model)
            tables.add(model._meta.db_table)


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(repair_missing_support_tables, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='support_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', '-created_at'], name='support_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_msg_ticket_created_idx'),
        ),
    ]
