# Generated by Django 5.2.8 on 2025-11-23 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('buying_method', models.CharField(choices=[('cash', 'Cash'), ('loan', 'Loan')], max_length=20)),
                ('is_cook_user', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('employment', models.CharField(blank=True, max_length=50, null=True)),
                ('economic_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_income', models.CharField(blank=True, max_length=50, null=True)),
                ('other_loans', models.CharField(blank=True, max_length=10, null=True)),
                ('grid_connection', models.CharField(blank=True, max_length=10, null=True)),
                ('cooking_fuel', models.TextField(blank=True, null=True)),
                ('stove_type', models.TextField(blank=True, null=True)),
                ('stove_usage', models.TextField(blank=True, null=True)),
                ('monthly_cooking_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('home_or_business', models.CharField(blank=True, max_length=20, null=True)),
                ('appliance_financed', models.CharField(blank=True, max_length=50, null=True)),
                ('repayment_period', models.CharField(blank=True, max_length=50, null=True)),
                ('utility_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('monthly_electricity_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('financier', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('address_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
