# Generated by Django 5.2.8 on 2025-11-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_checkoutorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
