# Generated by Django 5.2.8 on 2025-11-24 09:56

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_checkoutorder_payment_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutorder',
            name='stove_usage',
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='appliance_financed',
            field=models.CharField(blank=True, choices=[('electric_pressure_cooker', 'Electric Pressure cooker'), ('induction_cooker', 'Induction Cooker'), ('fridge', 'Fridge'), ('tv', 'TV'), ('electric_mill', 'Electric Mill'), ('air_conditioner', 'Air Conditioner')], null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='cooking_fuel',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('charcoal', 'Charcoal'), ('firewood', 'Firewood'), ('lpg', 'LPG'), ('electricity', 'Electricity'), ('biogas', 'Biogas'), ('briquettes', 'Briquettes'), ('ethanol', 'Ethanol'), ('pellets', 'Pellets'), ('kerosene', 'Kerosene'), ('sawdust', 'Sawdust'), ('other', 'Other')], max_length=90, null=True, verbose_name='Cooking Fuel Currently In Use'),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='education',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='employment',
            field=models.CharField(blank=True, choices=[('self_employed', 'Self Employed'), ('formal', 'Formal'), ('business_owner', 'Business Owner')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='financier',
            field=models.CharField(blank=True, choices=[('powerpayafrica', 'Powerpay Africa'), ('cms', 'CMS')], null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='grid_connection',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='home_or_business',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('business', 'Business')], null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='is_cook_user',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='monthly_cooking_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='monthly_electricity_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='monthly_income',
            field=models.CharField(blank=True, choices=[('below_30,000', 'Below Ksh 30,000'), ('30,000_50,000', 'Ksh 30,000 - Ksh 50,000'), ('50,000_100,000', 'Ksh 50,000 - Ksh 100,000'), ('above_100,000', 'Above Ksh 100,000')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='national_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='other_loans',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='repayment_period',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='stove_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('traditional_charcoal', 'Traditional Charcoal'), ('improved_charcoal', 'Improved Charcoal'), ('traditional_firewood', 'Improved Firewood'), ('lpg', 'LPG'), ('electric', 'Electric'), ('bio_ethanol', 'Bio-ethanol'), ('other', 'Other')], max_length=90, null=True, verbose_name='Cooking Stove Currently In Use'),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='utility_provider',
            field=models.CharField(blank=True, choices=[('kenya_power', 'Kenya Power'), ('other', 'Other')], null=True),
        ),
    ]
