# Generated by Django 5.2.8 on 2025-11-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_checkoutorder_stove_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='national_id',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
