# Generated by Django 5.2.8 on 2025-11-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_checkoutorder_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='national_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
