# Generated by Django 5.2.8 on 2025-11-25 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
