# Generated by Django 5.2.8 on 2026-08-19 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_user_is_vendor_approved_user_require_otp_and_more",
        ),
        (
            "shop",
            "0010_wishlist",
        ),
    ]

    operations = [

        # =========================================================
        # CHECKOUT ORDER - M-PESA FIELDS
        # These fields do NOT currently exist in the database.
        # =========================================================

        migrations.AddField(
            model_name="checkoutorder",
            name="checkout_request_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="checkoutorder",
            name="merchant_request_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="checkoutorder",
            name="mpesa_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="checkoutorder",
            name="mpesa_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="checkoutorder",
            name="mpesa_receipt",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="checkoutorder",
            name="mpesa_transaction_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="checkoutorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),

        migrations.AddField(
            model_name="checkoutorder",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
            ),
        ),

        # =========================================================
        # PRODUCT.max_stock
        #
        # The column ALREADY EXISTS in SQLite.
        # Update Django's migration state only.
        # =========================================================

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="product",
                    name="max_stock",
                    field=models.IntegerField(default=100),
                ),
            ],
        ),

        # =========================================================
        # PRODUCT RATING.review
        #
        # The column ALREADY EXISTS in SQLite.
        # Update Django's migration state only.
        # =========================================================

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="productrating",
                    name="review",
                    field=models.TextField(
                        blank=True,
                        null=True,
                    ),
                ),
            ],
        ),

        # =========================================================
        # SALE.order
        #
        # The column DOES NOT exist in SQLite.
        # Actually create it.
        # =========================================================

        migrations.AddField(
            model_name="sale",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="shop.checkoutorder",
            ),
        ),

        # =========================================================
        # CHECKOUT ORDER - payment_ref index
        #
        # Existing payment_ref has no database index.
        # The migration adds db_index=True.
        # =========================================================

        migrations.AlterField(
            model_name="checkoutorder",
            name="payment_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=200,
                null=True,
            ),
        ),

        # =========================================================
        # PRODUCT GALLERY
        #
        # The table ALREADY EXISTS in SQLite.
        # Update Django's state only.
        #
        # This also tells Django about the existing ProductGallery
        # -> Product relationship.
        # =========================================================

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="ProductGallery",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "image",
                            models.ImageField(
                                upload_to="product_gallery/",
                            ),
                        ),
                        (
                            "alt_text",
                            models.CharField(
                                blank=True,
                                max_length=255,
                            ),
                        ),
                        (
                            "product",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="gallery",
                                to="shop.product",
                            ),
                        ),
                    ],
                ),
            ],
        ),

        # =========================================================
        # PROMO CODE
        #
        # shop_promocode ALREADY EXISTS.
        # shop_promocode_products ALSO ALREADY EXISTS.
        #
        # Therefore update Django's state only.
        #
        # The ManyToMany relationship is part of CreateModel,
        # so Django will know about the existing
        # shop_promocode_products table without recreating it.
        # =========================================================

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="PromoCode",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "code",
                            models.CharField(
                                max_length=20,
                                unique=True,
                            ),
                        ),
                        (
                            "discount_type",
                            models.CharField(
                                choices=[
                                    ("percentage", "Percentage"),
                                    ("fixed", "Fixed Amount"),
                                ],
                                max_length=10,
                            ),
                        ),
                        (
                            "discount_value",
                            models.DecimalField(
                                decimal_places=2,
                                max_digits=10,
                            ),
                        ),
                        (
                            "is_active",
                            models.BooleanField(
                                default=True,
                            ),
                        ),
                        (
                            "usage_limit",
                            models.PositiveIntegerField(
                                blank=True,
                                null=True,
                            ),
                        ),
                        (
                            "used_count",
                            models.PositiveIntegerField(
                                default=0,
                            ),
                        ),
                        (
                            "valid_from",
                            models.DateTimeField(
                                default=django.utils.timezone.now,
                            ),
                        ),
                        (
                            "valid_to",
                            models.DateTimeField(
                                blank=True,
                                null=True,
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                            ),
                        ),
                        (
                            "products",
                            models.ManyToManyField(
                                blank=True,
                                related_name="promo_codes",
                                to="shop.product",
                            ),
                        ),
                        (
                            "vendor",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="promo_codes",
                                to="accounts.vendor",
                            ),
                        ),
                    ],
                ),
            ],
        ),
    ]