# Generated by Django 5.2.8 on 2026-08-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_checkoutorder_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutorder',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='checkoutorder',
            name='merchant_request_id',
        ),
        migrations.RemoveField(
            model_name='checkoutorder',
            name='mpesa_amount',
        ),
        migrations.RemoveField(
            model_name='checkoutorder',
            name='mpesa_phone',
        ),
        migrations.RemoveField(
            model_name='checkoutorder',
            name='mpesa_transaction_date',
        ),
        migrations.AddField(
            model_name='promocode',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=7),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
