# Generated by Django 5.2.8 on 2026-08-21 10:01

from django.db import migrations, models


def repair_missing_shop_tables(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        tables = set(schema_editor.connection.introspection.table_names(cursor))

    for model_name in ("ProductGallery", "PromoCode"):
        model = apps.get_model("shop", model_name)
        if model._meta.db_table not in tables:
            schema_editor.create_model(model)
            tables.add(model._meta.db_table)
            tables.update(field.remote_field.through._meta.db_table for field in model._meta.local_many_to_many)
        else:
            for field in model._meta.local_many_to_many:
                through = field.remote_field.through
                if through._meta.auto_created and through._meta.db_table not in tables:
                    schema_editor.create_model(through)
                    tables.add(through._meta.db_table)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_vendor_approved_user_require_otp_and_more'),
        ('shop', '0012_remove_checkoutorder_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.RunPython(repair_missing_shop_tables, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', '-created_at'], name='shop_prod_vendor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='shop_product_price_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['visibility', 'is_active', 'valid_to'], name='shop_promo_public_valid_idx'),
        ),
    ]
