# Generated by Django 5.2.8 on 2026-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_vendor_approved_user_require_otp_and_more'),
        ('shop', '0012_remove_checkoutorder_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', '-created_at'], name='shop_prod_vendor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='shop_product_price_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['visibility', 'is_active', 'valid_to'], name='shop_promo_public_valid_idx'),
        ),
    ]
