# Generated by Django 5.2.8 on 2026-08-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_repair_legacy_shop_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='warranty_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='warranty_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='warranty_signature',
            field=models.ImageField(blank=True, null=True, upload_to='warranty_signatures/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
