# Generated by Django 5.2.8 on 2026-08-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_checkoutorder_warranty_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
